<a href="https://colab.research.google.com/github/programacaodinamica/data-viz/blob/master/Pre_Processamento_Dados_COVID_para_Flourish%20(Aula%2002).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd

In [15]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [16]:
df_covid = pd.read_csv("/content/drive/MyDrive/Colab Datasets/HIST_PAINEL_COVIDBR_15jan2021.csv", sep=';')

In [17]:
df_covid.head()

   regiao estado  ... emAcompanhamentoNovos  interior/metropolitana
0  Brasil    NaN  ...                   NaN                     NaN
1  Brasil    NaN  ...                   NaN                     NaN
2  Brasil    NaN  ...                   NaN                     NaN
3  Brasil    NaN  ...                   NaN                     NaN
4  Brasil    NaN  ...                   NaN                     NaN

[5 rows x 17 columns]

In [18]:
covid_estados = df_covid.dropna( subset=['estado'])

In [19]:
covid_estados = covid_estados[pd.isnull(covid_estados['municipio'])]

In [21]:
covid_estados['letalidade'] = (covid_estados['obitosAcumulado']/covid_estados['casosAcumulado']).fillna(0)

In [22]:
covid_estados.head()

    regiao estado  ... interior/metropolitana  letalidade
328  Norte     RO  ...                    NaN         0.0
329  Norte     RO  ...                    NaN         0.0
330  Norte     RO  ...                    NaN         0.0
331  Norte     RO  ...                    NaN         0.0
332  Norte     RO  ...                    NaN         0.0

[5 rows x 18 columns]

In [23]:
covid_estados.to_csv('covid_estados_15jan21.csv')

In [50]:
df_covid_estados_bcr = pd.DataFrame(covid_estados.groupby(["estado","regiao","data"]).sum()['obitosAcumulado']).unstack()

In [51]:
df_covid_estados_bcr.columns = df_covid_estados_bcr.columns.droplevel()

In [52]:
df_covid_estados_bcr

data                 2020-02-25  2020-02-26  ...  2021-01-14  2021-01-15
estado regiao                                ...
AC     Norte                  0           0  ...         832         835
AL     Nordeste               0           0  ...        2601        2610
AM     Norte                  0           0  ...        5930        6043
AP     Norte                  0           0  ...         991         994
BA     Nordeste               0           0  ...        9611        9643
CE     Nordeste               0           0  ...       10209       10209
DF     Centro-Oeste           0           0  ...        4399        4406
ES     Sudeste                0           0  ...        5513        5534
GO     Centro-Oeste           0           0  ...        7020        7072
MA     Nordeste               0           0  ...        4588        4594
MG     Sudeste                0           0  ...       13138       13292
MS     Centro-Oeste           0           0  ...        2625        2648
MT     Centro-Oeste           0           0  ...        4674        4689
PA     Norte                  0           0  ...        7366        7376
PB     Nordeste               0           0  ...        3857        3869
PE     Nordeste               0           0  ...        9946        9964
PI     Nordeste               0           0  ...        2930        2935
PR     Sul                    0           0  ...        9052        9118
RJ     Sudeste                0           0  ...       27441       27591
RN     Nordeste               0           0  ...        3138        3149
RO     Norte                  0           0  ...        1976        1993
RR     Norte                  0           0  ...         806         811
RS     Sul                    0           0  ...        9790        9838
SC     Sul                    0           0  ...        5794        5836
SE     Nordeste               0           0  ...        2617        2629
SP     Sudeste                0           0  ...       49289       49600
TO     Norte                  0           0  ...        1294        1301

[27 rows x 326 columns]

In [53]:
df_covid_estados_bcr.to_csv('covid_estados_bcr_15jan21.csv')